// !DO NOT EDIT (generated by tools/gen-assets-def.js)
import { Resource } from 'Core/Resource';

export namespace ImageAssets {
  export const sample1 = new Resource('sample1', 'assets/images/sample1.png');
  export const sample2 = new Resource('sample2', 'assets/images/sample2.png');
}
